server:
  port: 8090

spring:
  application:
    name: flyway-db-migration

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/liquibase_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#use this command to generate chanagelog defaultSchema should be defined in liquibase config file
  # mvn liquibase:generateChangeLog - generate only tables
  # mvn liquibase:generateChangeLog -Dliquibase.diffTypes=data - generates tables with data