server:
  port: 8090

spring:
  application:
    name: flyway-db-migration

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/flyway_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


flyway:
  enabled: true
  locations: classpath:db/migration